name: CI Java

on:
  push:
    branches: main
    paths:
      - 'magoko-java/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - run: cd magoko-java && ./mvnw spotless:check && ./mvnw package -B
